apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyseerr
  namespace: { { .Values.namespace } }
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
      namespace: {{ .Values.gateway.namespace }}
  hostnames:
    - { { .Values.gateway.hosts.jellyseerr } }
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: jellyseerr
          port: { { .Values.ports.jellyseerr } }
      filters:
{{- if .Values.gateway.middlewares }}
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: {{ index .Values.gateway.middlewares 0 }}
            namespace: {{ .Values.gateway.namespace }}
{{- end }}