apiVersion: v1
kind: Service
metadata:
  name: vertex
  namespace: {{ .Values.namespace }}
  labels:
    app: vertex
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.vertex.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app: vertex
