apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: {{ .Values.namespace }}
  labels:
    app: radarr
spec:
  type: ClusterIP
  selector:
    app: radarr
  ports:
    - name: http
      port: {{ .Values.ports.radarr }}
      targetPort: http
