apiVersion: v1
kind: Service
metadata:
  name: xarr
  namespace: {{ .Values.namespace }}
  labels:
    app: xarr
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.xarr.ports.http }}
      targetPort: http
      protocol: TCP
  selector:
    app: xarr
