apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: {{ .Values.namespace }}
  labels: { app: sonarr }
spec:
  type: ClusterIP
  selector: { app: sonarr }
  ports:
    - name: http
      port: {{ .Values.ports.sonarr }}
      targetPort: http
