apiVersion: v1
kind: Service
metadata:
  name: bazarr
  namespace: {{ .Values.namespace }}
  labels: { app: bazarr }
spec:
  type: ClusterIP
  selector: { app: bazarr }
  ports:
    - name: http
      port: {{ .Values.ports.bazarr }}
      targetPort: http
