apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  storageClassName: {{ .Values.storage.class }}
