apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: {{ .Values.namespace }}
  labels:
    app: n8n
spec:
  type: ClusterIP
  selector:
    app: n8n
  ports:
    - name: http
      port: {{ .Values.ports.n8n }}
      targetPort: http
