apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    app: redis
spec:
  type: {{ .Values.service.type }}
  selector:
    app: redis
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: redis