namespace: media-center

images:
  sonarr: ghcr.io/linuxserver/sonarr:latest
  radarr: ghcr.io/linuxserver/radarr:latest
  bazarr: ghcr.io/linuxserver/bazarr:latest
  jellyseerr: fallenbagel/jellyseerr:latest
  qbittorrent: lscr.io/linuxserver/qbittorrent:latest
  vertex: lswl/vertex:latest
  xarr: xiaoyi510/xarr-rss:latest
  prowlarr: linuxserver/prowlarr:latest
  flaresolverr: flaresolverr/flaresolverr:latest

puid: 1027
pgid: 100
tz: Asia/Shanghai
umask: "022"

media:
  pvcName: nfs-media-pvc
  size: 20Ti
  accessModes:
    - ReadWriteMany

config:
  storageClassName: nfs-shared
  size: 2Gi
  accessModes:
    - ReadWriteMany

ports:
  sonarr: 8989
  radarr: 7878
  bazarr: 6767
  jellyseerr: 5055

qbittorrent:
  ports:
    webui: 8042
    bt: 51413
  hostNetwork: true
  nodeSelector:
    kubernetes.io/hostname: pi
  tolerations:
    - effect: NoSchedule
      key: tier
      operator: Equal
      value: light

vertex:
  ports:
    http: 3000
  resources:
    limits:
      cpu: 200m
      memory: 512M
    requests:
      cpu: 200m
      memory: 512M

xarr:
  ports:
    http: 8086
  resources:
    limits:
      cpu: 200m
      memory: 512M
    requests:
      cpu: 200m
      memory: 512M

prowlarr:
  ports:
    http: 9696
    nodePort: 30096

flaresolverr:
  ports:
    http: 8191

gateway:
  name: edge      # 你的 Gateway 名字
  namespace: traefik         # Gateway 所在命名空间
  entryPoints:
    - web
    - websecure
  tls: true                  # 是否启用 TLS
  middlewares:
    - sso-then-basic         # 中间件，已存在于 traefik namespace
  hosts:
    sonarr: sonarr.tuna.io
    radarr: radarr.tuna.io
    bazarr: bazarr.tuna.io
    jellyseerr: jellyseerr.tuna.io