apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      component: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
        component: postgresql
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: postgresql
          ports:
            - containerPort: {{ .Values.service.port }}
              name: postgresql
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.name | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.database.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.password | quote }}
            - name: POSTGRES_INITDB_ARGS
              value: "--auth-host=scram-sha-256"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-data-pvc
      restartPolicy: Always

