apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: postgresql
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: database
    component: postgresql

