# Default values for asf
image:
  repository: justarchibald/archi-steam-farm
  tag: "latest"

service:
  port: 1242

httproute:
  enabled: true
  hosts:
    - asf.tuna.io
  # Optional middlewares for HTTPRoute (array)
  middlewares: []
  namespace: services

# Storage configuration
persistence:
  enabled: true
  storageClass: ""  # Use default storage class
  accessMode: ReadWriteOnce
  size: 1Mi