# Default values for postgresql
image:
  repository: postgres
  tag: "15"

service:
  port: 5432

# Database configuration
database:
  name: "mydb"
  user: "postgres"
  password: "postgres123"
  postgresPassword: "postgres123"

# Storage configuration
persistence:
  enabled: true
  storageClass: "nfs-shared"
  accessMode: ReadWriteOnce
  size: 10Gi

# Resource limits
resources:
  requests:
    memory: "512Mi"
    cpu: "250m"
  limits:
    memory: "1Gi"
    cpu: "500m"

# Namespace
namespace: data

