{{- if .Values.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ddns-go-web
  namespace: {{ .Values.httproute.namespace }}
spec:
  parentRefs:
    - name: edge
      namespace: traefik
  hostnames:
    {{- range .Values.httproute.hosts }}
    - {{ . }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ddns-go-web
          port: {{ .Values.service.port }}
      {{- if .Values.httproute.middlewares }}
      filters:
        {{- range .Values.httproute.middlewares }}
        - type: ExtensionRef
          extensionRef:
            group: traefik.io
            kind: Middleware
            name: {{ . }}
            apiVersion: traefik.io/v1alpha1
        {{- end }}
      {{- end }}
{{- end }}