apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
      component: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
        component: mysql
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: mysql
          ports:
            - containerPort: {{ .Values.service.port }}
              name: mysql
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.database.rootPassword | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.database.name | quote }}
            - name: MYSQL_USER
              value: {{ .Values.database.user | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.database.password | quote }}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data-pvc
      restartPolicy: Always

