apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: mysql
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: database
    component: mysql

