{{- if .Values.ingress.enabled }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: asf-web
  namespace: traefik
spec:
  parentRefs:
    - name: edge
      namespace: traefik
  hostnames:
    {{- range .Values.ingress.hosts }}
    - {{ .host }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: asf-web
          port: {{ .Values.service.port }}
{{- end }}
