# Default values for ddns-go
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: jeessy/ddns-go
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 9876

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: ddns.opti.io
      paths:
        - path: /
          pathType: Prefix
  tls: []
  # Optional middleware for HTTPRoute
  middleware: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# Storage configuration
persistence:
  enabled: true
  storageClass: ""  # Use default storage class
  accessMode: ReadWriteOnce
  size: 1Mi
