name: Release Charts

on:
  push:
    branches: ["main"]
    paths:
      - "charts/**"
      - ".cr.yaml"
      - ".github/workflows/release.yml"
  workflow_dispatch:

concurrency:
  group: charts-release
  cancel-in-progress: false

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Helm lint
        run: |
          for d in charts/*; do
            [ -d "$d" ] && helm lint "$d"
          done

      - name: Install chart-releaser
        run: |
          curl -sSL https://github.com/helm/chart-releaser/releases/download/v1.6.1/chart-releaser_1.6.1_linux_amd64.tar.gz \
          | tar -xz
          sudo mv cr /usr/local/bin/cr

      - name: Package charts
        run: |
          mkdir -p .cr-release-packages
          cr package charts/*

      - name: Upload chart packages to GitHub Releases
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cr upload --skip-existing --owner rxrw --git-repo helm-charts --package-path .cr-release-packages

      - name: Ensure gh-pages branch exists (first run bootstrap)
        run: |
          set -e
          if ! git ls-remote --exit-code origin gh-pages >/dev/null 2>&1; then
            echo "Bootstrapping gh-pages..."
            git checkout --orphan gh-pages
            git reset --hard
            echo "apiVersion: v1" > index.yaml
            echo "entries: {}" >> index.yaml
            echo "generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> index.yaml
            git add index.yaml
            git -c user.name="github-actions[bot]" -c user.email="41898282+github-actions[bot]@users.noreply.github.com" commit -m "bootstrap gh-pages"
            git push -u origin gh-pages
            git checkout -f -
          fi

      - name: Configure git identity (for cr index push)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Build & push index.yaml to gh-pages
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cr index --push --owner rxrw --git-repo helm-charts --package-path .cr-release-packages --pages-branch gh-pages