name: Release Charts

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Install chart-releaser
        run: |
          curl -sSL https://github.com/helm/chart-releaser/releases/download/v1.6.1/chart-releaser_1.6.1_linux_amd64.tar.gz \
          | tar -xz
          sudo mv cr /usr/local/bin/cr

      - name: Package charts
        run: |
          mkdir -p .cr-release-packages
          cr package charts/*

      - name: Upload chart packages to GitHub Releases
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cr upload \
            --owner ${{ github.repository_owner }} \
            --git-repo ${{ github.event.repository.name }} \
            --skip-existing

      - name: Build index.yaml to gh-pages
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cr index \
            --owner ${{ github.repository_owner }} \
            --git-repo ${{ github.event.repository.name }} \
            --charts-repo https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

      - name: Publish gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # cr index 默认输出到 docs
          publish_branch: gh-pages
